# USER REGISTER
POST https://learn-it-mearn-stack.herokuapp.com/api/auth/register
Content-Type: application/json

{
    "username" :"hello2",
    "password" : "sieunhandienquang"
}
###

# USER LOGIN 
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" :"hello1",
    "password" : "sieunhandienquang"
}
###


# CREATED  POST
POST http://localhost:5000/api/posts
Content-Type:  application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0NTAxYmE5M2IwNGQ2ZDIwZDkyZmMiLCJpYXQiOjE2NTcyNjAxNjN9.XT3EikS-n5RwuqfvGEFoGNFgwvQfSK6Rsa9MEn508uU

{
    "title" : "This is first post",
    "description" : "abc",
    "url" : "google.com",
    "status" :"LEARNING"
}
###

# GET POST
GET  http://localhost:5000/api/posts
Content-Type:  application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0NzJmNjBlMGQxMDQwNjczOWIxNTgiLCJpYXQiOjE2NTcwNDE2NjR9.kEWMwU2qWTAHIbt3HIm012C0aBTYUyFjQuJIv9NV084
###

# UPDATE POST
PUT  http://localhost:5000/api/posts/62c472cf0e0d10406739b151
Content-Type:  application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0NTAxYmE5M2IwNGQ2ZDIwZDkyZmMiLCJpYXQiOjE2NTcwNDA3ODF9.7LBs580RCxZUS3vQFsmtJ1bOy3Bb-kEWg9a9yfxwczI

{
      "title": "This is UPDATED 2 times  post",
      "url": "google.com",
      "description": "abc",
      "status": "LEARNING"
}
###

# DELETE POST
DELETE   http://localhost:5000/api/posts/62c47c6711096417ba155392
Content-Type:  application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MmM0NzJmNjBlMGQxMDQwNjczOWIxNTgiLCJpYXQiOjE2NTcwNDE2NjR9.kEWMwU2qWTAHIbt3HIm012C0aBTYUyFjQuJIv9NV084

###
